import {StyleSheet, Dimensions} from 'react-native';
const {width} = Dimensions.get('window');

const styles2 = StyleSheet.create({
  width: '100%',
  homeContainer: {
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: 'black',
  },
  navbar: {
    width: '100%',
    diplay: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#6A0DAD',
    flexDirection: 'row',
    gap: 15,
    paddingVertical: 15,
    position: 'static',
    top: 0,
  },
  navbarSearch: {
    height: 40,
    width: '70%',
    borderColor: 'white',
    borderWidth: 1,
    borderRadius: 100,
    paddingHorizontal: 20,
  },
  sideBar: {
    flex: 1,
    width: '100%',
    height: '100%',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  sideBarUser: {
    backgroundColor: '#B388FF',
    padding: 20,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    alignItems: 'start',
    width: '80%',
    gap: 20,
  },
  textTitle: {
    fontWeight: 'bold',
    fontSize: 16,
    color: 'white',
  },
  textTitleCenter: {
    textAlign: 'center',
  },
  sideBarOption: {
    display: 'flex',
    flexDirection: 'row',
    gap: 10,
    alignItems: 'center',
  },
  btnPrimary: {
    backgroundColor: '#6A0DAD',
    padding: 10,
    borderRadius: 10,
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconProfile: {
    backgroundColor: 'white',
    borderRadius: 100,
    padding: 10,
    height: 70,
    width: 70,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  sideBarUserContainer: {
    display: 'flex',
    flexDirection: 'row',
    gap: 5,
    alignItems: 'center',
  },
  sideBarUserText: {
    display: 'flex',
    width: '75%',
    flexDirection: 'column',
    gap: 10,
    padding: 10,
    alignItems: 'start',
  },
  sideBarOptions: {
    width: '80%',
    height: '100%',
    backgroundColor: '#2B2B2B',
    display: 'flex',
    flexDirection: 'column',
    gap: 20,
    padding: 20,
  },
  slider: {
    width: width,
    display: 'flex',
    justifyContent: 'start',
    alignItems: 'start',
    padding: 10,
    gap: 10,
  },
  sliderImg: {
    resizeMode: 'cover',
    width: '100%',
    height: 200,
    overflow: 'hidden',
    borderRadius: 15,
  },
  initialProm: {
    backgroundColor: 'black',
    color: 'white',
    textAlign: 'center',
    padding: 10,
    borderRadius: 10,
    fontSize: 12,
  },
  categoryItem: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 10,
    padding: 10,
    backgroundColor: '#6A0DAD',
    borderRadius: 10,
    margin: 10,
    width: 130,
  },
  btnCategoryImg: {
    backgroundColor: 'white',
    borderRadius: 100,
    width: 90,
    height: 90,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  categoryImg: {
    width: 50,
    height: 50,
    resizeMode: 'contain',
  },
  cardProduct: {
    display: 'flex',
    flexDirection: 'column',
    padding: 10,
    gap: 10,
    borderRadius: 10,
    margin: 10,
    width: 150,
  },
  imgProductContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
    borderRadius: 10,
    padding: 10,
  },
  imgProduct: {
    width: 150,
    height: 150,
    resizeMode: 'contain',
  },
  sectionContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: 20,
    paddingVertical: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sectionBg: {
    backgroundColor: '#2B2B2B',
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    width: '95%',
    padding: 10,
    borderRadius: 10,
  },
  textBtn: {
    color: 'white',
    textAlign: 'center',
    fontWeight: 'bold',
    fontSize: 12,
  },
  textProductContainer: {
    display: 'flex',
    flexDirection: 'column',
    paddingHorizontal: 10,
  },
  bgScreen: {
    backgroundColor: '#2B2B2B',
    height: '100%',
    width: '100%',
  },
  btnBack: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: 10,
    alignSelf: 'flex-start',
  },
  iconApp: {
    height: 130,
    width: 130,
  },
  signInContainer: {
    backgroundColor: '#6A0DAD',
    display: 'flex',
    flexDirection: 'column',
    gap: 20,
    paddingVertical: 60,
    paddingHorizontal: 20,
    borderTopRightRadius: 40,
    borderTopLeftRadius: 40,
    width: '100%',
    position: 'absolute',
    bottom: 0,
  },
  textInputLabel: {
    textAlign: 'start',
    color: 'white',
    fontSize: 12,
    marginLeft: 10,
  },
  textInput: {
    backgroundColor: 'white',
    padding: 10,
    borderRadius: 10,
    color: 'black',
  },
  textInput2: {
    borderWidth: 1,
    borderColor: 'white',
    padding: 10,
    borderRadius: 10,
    color: 'white',
    width: '100%',
  },
  btnSecondary: {
    backgroundColor: '#B388FF',
    padding: 15,
    borderRadius: 10,
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnThird: {
    borderColor: 'white',
    padding: 15,
    borderRadius: 10,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'flex-start',
    gap: 10,
    borderWidth: 1,
  },
  inputSection: {
    display: 'flex',
    flexDirection: 'column',
    gap: 5,
  },
  inputSectionMid: {
    width: '48%',
  },
  inputSectionGrid: {
    width: '30%',
  },
  btnSection: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
  },
  signUpScreen: {
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    gap: 20,
    backgroundColor: '#2B2B2B',
  },
  signUpScreenContainer: {
    padding: 20,
  },
  textPrincipal: {
    color: 'white',
    fontSize: 30,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 20,
  },
  formSection: {
    display: 'flex',
    flexDirection: 'column',
    gap: 20,
  },
  btnDate: {
    color: 'black',
    backgroundColor: 'white',
    borderRadius: 10,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  dateTimeText: {
    color: 'black',
    fontSize: 16,
    fontWeight: 'bold',
  },
  rowInputsContainer: {
    display: 'flex',
    gap: 10,
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'center',
  },
  picker: {
    borderWidth:1,
    borderColor:'white',
    color: 'black',
    borderRadius:10,
  },
});

export {styles2};
